# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JJWhiteDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JJWhiteDemo

  pod 'White-SDK-iOS'
  pod 'Masonry'
  pod 'AgoraRtcEngine_iOS'
  pod 'MBProgressHUD'
  target 'JJWhiteDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JJWhiteDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
